### ISSUE TITLE
Creating new estimate session based on handpicked user stories gives 404

### ISSUE THREAD

**Issue by DennisvandenBelt** [microsoft/azure-boards-estimate#219]
Hi all,

Today I wanted to create a new estimate session based on some handpicked user stories form the board (right click -> "Estimate work item(s)"). After the selection I get redirected to the estimate tab, but shows up blank. There are no options to chose from. See image below.
![image](https://user-images.githubusercontent.com/126078434/220623804-3af26339-f842-4ee4-8728-a6765bc2b0ce.png)

I do see that the fetch failed, but don't know why. Last thursday was the last time I used it (succesfully). Is there anyone to help me out or to put me in the right direction to resolve this issue?

![image](https://user-images.githubusercontent.com/126078434/220624941-e2a2a2a1-573e-44ca-be8f-d961c6fb851c.png)

**Comment by AminTi** [comment]
Thanks for reporting!

**Comment by Nick0-8** [comment]
My company is noticing a similar problem. It started last week and they can no longer use the estimation feature by selecting work items from the backlog view

**Comment by AminTi** [comment]
It works as expected for me, It should be something with your environment. can you describe it? Can you see any error in the console?

**Comment by DiegoCuevasSanchez** [comment]
I get the same results, blank screen. No errors on console. This only occurs when creating a session from the backlog. I was able to create from query successfully, but it is very time consuming.

**Comment by AminTi** [comment]
it works for me, I will dig into this again.

**Comment by dwkroeze** [comment]
same issue with the estimate, also a 404 error

![image](https://user-images.githubusercontent.com/18441673/221126598-73a97c59-f2a7-45d8-8f99-8a30c24537fc.png)

**Comment by dwkroeze** [comment]
same issue with the estimate, also a 404 error

![image](https://user-images.githubusercontent.com/18441673/221128787-4e26674c-b79c-43bd-b5a1-7b8a5777012d.png)

**Comment by DennisvandenBelt** [comment]
> It works as expected for me, It should be something with your environment. can you describe it? Can you see any error in the console?

I've put all the information I have on the error in the initial post. A more detailed description of the error is deliverd by dwkroeze.

**Comment by zapftho** [comment]
We are having the same issue on our end since a few days.

**Comment by BalaJi2302** [comment]
Even I am facing the same issue at our end. A quick resolution would be much helpful as we heavily rely on this for our refinement sessions in our organisation.

**Comment by ssteiner1** [comment]
We are also facing this issue.  Following for updates.  Thanks!

**Comment by jbamberski** [comment]
There is a good alternative on the marketplace w/o this issue:
[Planning Poker for Azure](https://marketplace.visualstudio.com/items?itemName=SpartezSoftware.planning-poker-azure)

**Comment by AminTi** [comment]
Hi guys, Does anyone wants to join me on a web session? I could not reproduce the issues.

**Comment by DennisvandenBelt** [comment]
@AminTi we can meet up so I can show you what is going on. However I'm very new to this forum and can't find a way to send you a private message.

**Comment by AminTi** [comment]
amin.titi@solidify.dev team meeting

**Comment by DennisvandenBelt** [comment]
@AminTi I've send you a Teams invite by email. Thank you for the quick response. Please feel free to postpone the meeting.

**Comment by AminTi** [comment]
Thanks see you soon

**Comment by AminTi** [comment]
Resolved

**Comment by zapftho** [comment]
@AminTi Is this really fixed? I am no longer getting an empty page but if I try to create a new sessions from within the backlog I get no new session created. It returns an empty sessions screen without any sessions created. So still not able to crate any Sessions from the backlog.

**Comment by DennisvandenBelt** [comment]
@zapftho Same here. I already contacted @AminTi by email about the changes. Perhaps we're missing something (update of the plugin?).

**Comment by dwkroeze** [comment]
same here. Can't create a session

**Comment by AminTi** [comment]
Hi again. I just released an update. It should work.

**Comment by DennisvandenBelt** [comment]
Good morning Amin,

Yes it works again! Thanks a lot!


Met vriendelijke groet,

Dennis van den Belt
Scrum master

***@***.***
+31 347 329 600
***@***.***
***@***.******@***.***>
***@***.***
www.cadac.com<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cadac.com%2Femail-1&data=04%7C01%7CJohn.Billekens%40sltn.nl%7C638575d7378f4d8de06c08d9fb97e3e7%7Cd63ae20e04f340b4983187cf60173c90%7C0%7C0%7C637817452069946263%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y1SH3M1rNEgdvU9oaRs2J9tmGl23WSMygQ9X4zayp3Q%3D&reserved=0>
Cadac Group BV
Laanakkerweg 6
4131 PA Vianen
***@***.***<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cadac.com%2Femail-2&data=04%7C01%7CJohn.Billekens%40sltn.nl%7C638575d7378f4d8de06c08d9fb97e3e7%7Cd63ae20e04f340b4983187cf60173c90%7C0%7C0%7C637817452069946263%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EaeyAQ7bUrsvFx5KIa4w%2BXCBxLVmcagO9U7PkTaNWjQ%3D&reserved=0>
[Afbeelding met tekst  Automatisch gegenereerde beschrijving]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.cadac.com%2Femail-3&data=04%7C01%7CJohn.Billekens%40sltn.nl%7C638575d7378f4d8de06c08d9fb97e3e7%7Cd63ae20e04f340b4983187cf60173c90%7C0%7C0%7C637817452069946263%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vvAnG3sA6jvREmxMYxtgygF%2B4S2XZ0mKZPwmCuVe6Zk%3D&reserved=0>



Van: AminTi ***@***.***>
Verzonden: zondag 5 maart 2023 01:02
Aan: microsoft/azure-boards-estimate ***@***.***>
CC: Dennis van den Belt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/azure-boards-estimate] Creating new estimate session based on handpicked user stories gives 404 (Issue #219)


Hi again. I just released an update. It should work.

**Comment by dwkroeze** [comment]
thanks, working again

**Comment by zapftho** [comment]
Thanks, I can also confirm it is working again.
